### ISSUE TITLE
能否提交下upload img下的几个图片文件

### ISSUE THREAD

**Issue by gakaki** [shen100/wemall#7]
config 文件都是dev开头的...
很好的项目谢谢 star了

**Comment by shen100** [comment]
@gakaki   

dev的config文件要改名，去掉dev，文档已补充  
upload的图片已提交  

* **修改配置文件**  
进入wemall目录，将`configuration.dev.json`改名为`configuration.json`, 再找到`UploadImgDir`，填写图片上传目录为 `{项目目录}/upload/img`, 举例：C:\dev\src\wemall\upload\img (Windows系统）或 /dev/src/wemall/upload/img (Mac OS X 或Linux系统)
  
```
{
  "go": {
    "UploadImgDir": "" /*图片上传的目录*/
  }
}
```
