### ISSUE TITLE
nodejs里的2个项目具体应该怎么才能跑起来啊

### ISSUE THREAD

**Issue by gakaki** [shen100/wemall#8]
npm start 之后404啊

**Comment by shen100** [comment]
@gakaki   
  
* **配置nginx**
将`wemall/nginx/dev.wemall.com.conf`文件拷贝到nginx的虚拟主机目录下, 再将`wemall/nginx/server.key`和`wemall/nginx/server.crt`拷贝到某个目录下，然后修改nginx的虚拟主机目录下的`dev.wemall.com.conf`文件中`server.key`和`server.crt`的路径  

* **配置hosts**    
127.0.0.1 dev.wemall.com

* **访问网站后台**
在浏览器地址栏中输入https://dev.wemall.com/admin
